export const products = [
  {
    id: 1,
    title: "Double Monk",
    slug: "double-monk",
    category: "Officials",
    size: "8",
    price: 45,
    images: ["/images/double-monk-1.jpg", "/images/double-monk-2.jpg"],
    label: "",
    rating: 5,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis consectetur corporis velit repellat commodi aliquid ullam sapiente quaerat eaque totam molestiae nobis ducimus, labore reiciendis eius recusandae at sint suscipit id consequatur nisi, inventore excepturi est. Ad itaque odit atque animi. Autem neque veniam vel sequi tenetur distinctio fuga repellat aut! Inventore, dolore iste. Inventore qui aspernatur sequi quibusdam expedita?",
  },
  {
    id: 2,
    title: "Billionaire boots",
    slug: "billionaire-boots",
    category: "Boots",
    size: "7",
    price: 48,
    images: [
      "/images/billionaire-boot-1.jpg",
      "/images/billionaire-boot-2.jpg",
    ],
    label: "featured",
    rating: 4.5,
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos asperiores optio illo quo tenetur sequi est qui deleniti deserunt. Corporis rerum neque recusandae harum repellat itaque consequatur, praesentium debitis hic cum placeat, ea atque temporibus magnam, facilis suscipit. Commodi magnam, obcaecati aliquid ullam esse asperiores saepe porro doloremque corporis iste.",
  },
  {
    id: 3,
    title: "Leather boots",
    slug: "leather-boots",
    category: "Boots",
    size: "7",
    price: 49,
    images: [
      "/images/leather-boots-1.jpg",
      "/images/leather-boots-2.jpg",
      "/images/leather-boots-3.jpg",
    ],
    label: "new",
    rating: 4.8,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, illum molestias perspiciatis, ad consequatur incidunt quisquam quia fugiat vitae omnis nostrum eveniet architecto quibusdam tenetur veritatis mollitia labore nemo, soluta iusto! Sequi ipsam debitis accusantium numquam ducimus nam error voluptatum.",
  },
  {
    id: 4,
    title: "Official",
    slug: "official",
    category: "Officials",
    size: "7",
    price: 49,
    images: ["/images/officials-1.jpg", "/images/officials-2.jpg"],
    label: "featured",
    rating: 5,
    description:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod ab doloremque eveniet? Harum quaerat error delectus dolor natus nobis molestiae veritatis quidem labore qui blanditiis provident laudantium soluta praesentium magni cupiditate quam temporibus sapiente, officia dolore debitis assumenda quas quasi pariatur! Quod beatae laborum cum, ab quasi hic minima eligendi at doloremque laboriosam aliquid. Suscipit quod reprehenderit et consequuntur voluptates.",
  },
  {
    id: 5,
    title: "Nike SB",
    slug: "nike-sb",
    categoty: "sneakers",
    size: "7",
    price: 35,
    images: [
      "/images/nike-sb-1.jpg",
      "/images/nike-sb-2.jpg",
      "/images/nike-sb-3.jpg",
    ],
    label: "featured",
    rating: 5,
    description: "",
  },
  {
    id: 6,
    title: "Addidas Campus",
    slug: "addidas-campus",
    category: "sneakers",
    size: "8",
    price: 45,
    images: [
      "/images/addidas-campus-1.jpg",
      "/images/addidas-campus-2.jpg",
      "/images/addidas-campus-3.jpg",
      "/images/addidas-campus-4.jpg",
    ],
    label: "new",
    rating: 4.8,
    description: "",
  },
  {
    id: 7,
    title: "Jordan 11",
    slug: "jordan-11",
    category: "sneakers",
    size: "9",
    price: 55,
    images: [
      "/images/jordan11-1.jpg",
      "/images/jordan11-2.jpg",
      "/images/jordan11-3.jpg",
      "/images/jordan11-4.jpg",
    ],
    label: "",
    rating: 4.5,
    description: "",
  },
  {
    id: 8,
    title: "Jordan 1",
    slug: "jordan-1",
    category: "sneakers",
    size: "10",
    price: 45,
    images: [
      "/images/jordan1-1.jpg",
      "/images/jordan1-2.jpg",
      "/images/jordan1-3.jpg",
      "/images/jordan1-4.jpg",
    ],
    label: "new",
    rating: 5,
    description: "",
  },
  {
    id: 9,
    title: "Officials Men",
    slug: "officials-men",
    category: "Officials",
    size: "7",
    price: 50,
    images: ["/images/officials-men.jpg", "/images/officials-men-2.jpg"],
    label: "new",
    rating: 4.9,
    description: "",
  },
  {
    id: 10,
    title: "Official Boots",
    slug: "official-boots",
    category: "Boots",
    size: "8",
    price: 35,
    images: [
      "/images/official-boots-1.jpg",
      "/images/official-boots-2.jpg",
      "/images/official-boots-3.jpg",
    ],
    label: "featured",
    rating: 4.9,
    description: "",
  },
];
